### ISSUE TITLE
Suggestion: HTML/CSS to styled component, use class name instead

### ISSUE THREAD

**Issue by mbcod3** [springload/metacomponent#1]
Thanks for creating this. Its helpful to convert html css into styled component but by default it uses html tag as styled component name. it would be great if it used class name of that html element instead. e.g.

```
<div class="container">
</div>
```

it converts that into

`<StyledDiv></StyledDiv>`

It would be great if it did

`<StyledContainer></StyledContainer>`

once again thanks for creating this.

**Comment by holloway** [comment]
Interesting idea, thanks. If there were multiple classes would the name be?

**Comment by mbcod3** [comment]
Then you can fall back to current naming. 

Also there is a bug where if an element div has psuedo elements such as ::before in css styles, when converted to styled component it gives those styles to the element it self i.e. div.

Another suggestion is that if n number of elements have the same class, it should create one styled component and reuse it instead of creating n number of styled components. e.g.

```
<a href="" class="link">about</a>
<a href="" class="link">about</a>
```
It converts that to

```
const styledA = styled.a``
const styledA_2 = styled.a``
```

since its the same class with the same styles it should reuse Link component instead of creating n numbers of components.


I started using it but in its current form its not that usefull but I appreciate your effort. Converting html/css to styled components manually is so painful and unnecassary labor and time which can be used in more productive way.

**Comment by holloway** [comment]
What about something like `data-name="SomeName"` ?

**Comment by mbcod3** [comment]
So you mean the html element should have data-name attribute before hand? If thats the case I think thats not practical. Basically converting html to react jsx or styled component etc. the last thing we need is to manually change the html before using meta component converter. The whole point is to automate conversion.

Imo first class name as the name of styled component makes sense. It doesnt matter if there are multiple classes, it will use just the first class name. This way the code doesnt look auto generated which it does right now with styledDiv and styledDiv_2 naming convention.

If you implement these two suggestions, first I wrote in previous reply and second being this one, I would definitely use meta component. In its current form I cant.

**Comment by holloway** [comment]
Ok thanks. I'll think about it.

**Comment by mbcod3** [comment]
Thanks for creating meta component and listening to my suggestions.
